// Original graded retellings of public-domain classics. Not quotations or full chapters.
window.LINGO_CLASSICS=[];
(() => {
const books={garden:['秘密花园','The Secret Garden','Frances Hodgson Burnett','https://www.gutenberg.org/ebooks/113'],anne:['绿山墙的安妮','Anne of Green Gables','L. M. Montgomery','https://www.gutenberg.org/ebooks/45'],women:['小妇人','Little Women','Louisa May Alcott','https://www.gutenberg.org/ebooks/514'],oz:['绿野仙踪','The Wonderful Wizard of Oz','L. Frank Baum','https://www.gutenberg.org/ebooks/55'],alice:['爱丽丝漫游奇境','Alice’s Adventures in Wonderland','Lewis Carroll','https://www.gutenberg.org/ebooks/11']};
function add(book,n,title,cn,level,text,guide,vocab,focus,prompt){const b=books[book];window.LINGO_CLASSICS.push({id:`classic-${book}-${n}`,level,title,cn:`《${b[0]}》选段 ${n} · ${cn}`,kind:'名著分级改写',book:b[0],sourceTitle:b[1],author:b[2],source:b[3],adapted:true,paragraphs:text.trim().split('\n\n'),translation:[guide],words:vocab,focus,prompt});}
add('garden',1,'A House Full of Doors','满是房门的大宅','A2',`
Mary arrived at her uncle's house on a cold evening. The building was much larger than any home she knew. There were many windows, but only a few of them showed light. Inside, long passages led to closed doors. A woman took Mary upstairs and told her which rooms she could use. Mary wanted to ask about the others, but the woman was already walking away.

The next morning, a young servant named Martha came into the room. Martha spoke to Mary in a friendly way. This surprised Mary, who was used to giving orders. When Mary expected help with every part of getting dressed, Martha explained that children in her own family dressed themselves. Mary was annoyed. However, there was nobody else to help, so she began to try.

Martha talked about her home and her brothers and sisters. They had little money, but they played outside and found interesting things everywhere. Her brother Dickon knew the animals on the moor. Mary listened without saying much. She had never thought that a poor family could have so many things to talk about. Her own days often seemed empty, even when people did everything for her.

After breakfast, Mary went outside. The wind was strong, and she pulled her coat around her. She walked past walls, paths and garden gates. Somewhere beyond the house, a small bird was singing. Mary stopped to listen. She did not suddenly feel happy, and she still disliked many things about her new home. Yet she wanted to know where the bird was hiding. For the first time since arriving, she had a reason to walk a little farther. Behind her, the house was still full of closed doors. Outside, however, there were paths she had not yet followed. She chose one and began to explore it.
`, '玛丽来到叔叔的大宅，起初仍习惯命令别人。玛莎谈起家人与户外生活，让她开始好奇。她走出房间寻找鸟声：故事的变化从愿意探索开始。',[['passage','n.','走廊；通道'],['servant','n.','仆人'],['be used to doing','短语','习惯做……'],['moor','n.','荒野；旷野']], 'was used to giving orders：be used to + 名词/doing，表示习惯；不要与 used to do（过去常常）混淆。','玛莎的生活和玛丽的生活有什么不同？用三句英语比较。');
add('garden',2,'The Key in the Earth','泥土中的钥匙','A2',`
Mary began to spend more time outside. She did not have a friend to walk with, but a small robin often appeared near her. It moved along the ground and watched her with bright eyes. Mary spoke to it as if it could understand every word. The bird did not answer, of course, but it did not fly away immediately either. That was enough to make her feel less alone.

She had heard about a garden that had been closed for years. Her uncle did not want anyone to enter it. The door was locked, and the key had disappeared. Mary thought about this garden whenever she passed the high walls. What happened to flowers when nobody looked after them? Could a garden keep growing without people? She searched for a door, but leaves covered much of the wall.

One day, the robin landed close to a place where the earth had been disturbed. Mary looked down and noticed something that was not a stone. She moved some soil with her fingers. Under it was an old key. It was dirty and looked as if it had been there for a very long time. Mary held it tightly. She could not be certain what it opened, but she immediately thought of the secret garden.

A little later, the wind moved the hanging leaves on the wall. For a moment, Mary could see a small part of a wooden door. She hurried towards it and pushed the leaves aside. The key went into the lock. She turned it carefully, afraid that it might break. Then the door opened. Mary stepped through and closed it behind her. Everything was quiet. Dry branches stood above the paths, and old plants covered the ground. To another person, the garden might have looked forgotten. To Mary, it looked like a place that was waiting for someone. She wanted to be that person.
`, '知更鸟陪伴玛丽探索。她在翻动过的泥土里发现旧钥匙，后来又看到被枝叶遮住的门。花园虽然荒凉，却激起她照料它的愿望。',[['robin','n.','知更鸟'],['soil','n.','土壤'],['lock','n.','锁'],['look after','短语','照料']], 'as if it could understand：as if 引出“好像……”；could 在这里描述想象中的能力。','按顺序说清她如何找到钥匙、发现门、进入花园。');
add('garden',3,'A Friend Who Understood Plants','懂植物的朋友','B1',`
Finding the garden was only the beginning. Mary wanted to help it grow, but she knew almost nothing about plants. When she saw small green points coming through the soil, she carefully cleared the space around them. She worried that she might pull up something useful by mistake. She needed advice from someone who would understand why this place mattered and would not immediately tell everyone about it.

Martha had often spoken about her brother Dickon. When Mary finally met him, he was outside with animals close by. He did not seem to frighten them. There was something calm about the way he moved and spoke. Mary asked him questions about growing things. He answered without laughing at her lack of knowledge. This made it easier to ask another question, and then another.

Eventually, Mary decided to trust him with her secret. She took him through the hidden door. Dickon looked around slowly. He examined branches that Mary had thought were dead and showed her how to look for signs of life. Not everything would grow again, but more of the garden was alive than she had expected. Instead of seeing only a great amount of work, Mary began to see possibilities.

They worked together, making space for young plants and discussing where new flowers might go. Mary forgot to think about how unhappy she usually was. She was too busy carrying things, asking questions and checking the ground. When she became tired, it was the pleasant tiredness that came after doing something useful. The garden did not change completely in a single afternoon, and neither did Mary. Some paths were still untidy when they stopped. Yet she could point to small places that looked better because of their work. She also had someone with whom she could share tomorrow's plans. A secret had brought her into the garden alone; caring for it was teaching her how to have a friend.
`, '玛丽发现花园后缺乏园艺知识。她信任迪肯，把秘密告诉他。共同劳动使她既看到植物的生机，也体验到平等交流的友谊。',[['examine','v.','检查；仔细观察'],['branch','n.','树枝'],['possibility','n.','可能性'],['by mistake','短语','错误地；无意中']], 'branches that Mary had thought were dead：that 引导定语从句，修饰 branches；had thought 表示比当时观察更早的判断。','为什么玛丽愿意信任迪肯？从他的态度和行为找出依据。');
add('garden',4,'Someone Beyond the Curtain','帘子后的人','B1',`
One night, Mary heard crying somewhere in the house. At first, she thought it might be the wind. Then the sound came again, and she knew that a person was crying. She left her room and followed the noise through the passages. Behind a door, she found a boy lying in a large bed. He looked pale and surprised. He had not expected a girl to appear in his room at night.

The boy was her cousin Colin. Mary had not known that he lived in the house. He spent much of his time in bed and believed that he would always be weak. Adults spoke quietly around him and often gave him whatever he demanded. Mary recognised something familiar in his behaviour. She, too, had once expected everyone to do exactly what she wanted. Unlike the adults, she was not afraid to disagree with him.

They talked about the world outside. Mary described the wind, the robin and the things that were beginning to grow. Colin listened with an attention that surprised her. His room contained many comfortable objects, but it could not give him the experience of standing under a tree. The more she talked, the more he wanted to see a garden himself. Mary had to decide how much of her secret to share.

Their friendship did not become easy all at once. Colin could be angry and demanding, and Mary could be impatient. Still, they offered each other something that had been missing. He had someone of his own age to talk to; she had someone who was interested in her discoveries. Later, with help, Colin would visit the hidden garden. His progress would take time rather than happen like a sudden spell. This first conversation was important because it changed the shape of his days. Instead of imagining only what might go wrong, he could begin to imagine a place he wanted to reach. Beyond his curtains, a world was waiting.
`, '玛丽循着哭声发现表弟科林。他长期待在房里，害怕自己一直虚弱。玛丽的户外经历给他新的期待；改写强调相处与逐渐变化，不把康复写成瞬间的奇迹。',[['curtain','n.','窗帘'],['pale','adj.','苍白的'],['demand','v.','强烈要求'],['impatient','adj.','不耐烦的']], 'The more she talked, the more he wanted…：the + 比较级，the + 比较级，表示“越……越……”。','玛丽和科林有哪些相似点？他们又怎样帮助对方？');
add('anne',1,'A Girl at the Station','车站上的女孩','A2',`
Matthew went to the station to meet a child. He and his sister Marilla had asked for a boy who could help on their farm. Matthew did not talk much, and meeting a stranger made him nervous. When he reached the station, he saw a thin girl sitting beside her bag. There was no boy waiting. The girl had red hair, bright eyes and a great deal to say.

Her name was Anne. She explained that she had been waiting for him and had already thought about what to do if he did not come. Perhaps she could sleep in a tree, she said. Matthew did not know how to explain the mistake. He decided to take her home and let Marilla decide what should happen. Anne climbed into the carriage, happy that someone had finally arrived for her.

On the journey, Anne talked about almost everything she saw. A road was not simply a road to her. The trees could make it seem like a beautiful passage into another world. Water shining in the evening light needed a special name. Matthew had travelled this way many times, but he had never heard anyone describe it like that. He listened while Anne filled the quiet journey with words.

Then Green Gables came into view. Anne looked at the house and imagined living there. She wanted a place where she would not have to leave again. Matthew felt the weight of the news he had not yet told her. To him, she was no longer only the wrong child from the station. She was a real person who was excited, hopeful and afraid of being unwanted. He still did not know what Marilla would say. But as they came closer to the house, he began to wish that the mistake might not have to be corrected by sending Anne away. The journey had changed what he hoped would happen next.
`, '马修本来去接能帮农场干活的男孩，却遇见安妮。回家途中，她富有想象力的话语打动了沉默的马修。他开始希望她能留下。',[['station','n.','车站'],['carriage','n.','马车'],['stranger','n.','陌生人'],['come into view','短语','进入视野']], 'had asked for a boy：过去完成时，说明“提出请求”早于“去车站接人”。先读懂事件顺序即可。','马修出发前和到家时的想法有何不同？');
add('anne',2,'A Place to Stay','可以留下的地方','B1',`
Marilla was surprised when Matthew brought a girl home. She explained that they had asked for a boy, not a girl. Anne's happy expression disappeared. During the journey, she had begun to imagine Green Gables as her home. Now she understood that the people who lived there had not been expecting her at all. She felt that another door was closing before she had properly entered it.

Marilla was not a cruel person, but she liked clear arrangements. A mistake had happened, and she thought that it needed to be put right. Matthew said little. However, his few words showed that he wanted Anne to stay. He had heard her talk, seen her excitement and understood something of her loneliness. For him, the question was already more personal than practical.

As Marilla learned about Anne's earlier life, the decision became harder. Anne had moved between places where she was useful to adults but did not truly belong. She had looked after younger children and had learned to fill lonely hours with imagination. Her dramatic way of speaking could seem strange, yet behind it was a simple wish: she wanted someone to choose her, rather than merely accept her help.

Marilla considered what might happen if Anne were sent away. She also began to see that keeping her would mean more than providing a bed. The girl would need education, guidance and patience. There would be mistakes, difficult conversations and work that a farm boy would not have required. Eventually, Anne was allowed to remain at Green Gables. The choice did not turn Marilla into a person who easily showed every feeling. She would still be firm, and Anne would still talk too much at times. But the house had made room for someone it had not expected. For Anne, that changed the meaning of ordinary things: a room, a meal and tomorrow morning could now be parts of a life she was allowed to keep.
`, '玛丽拉重视原先的安排，但了解安妮的经历后重新考虑。让她留下不仅是提供住处，也意味着长期的关心与教育。',[['arrangement','n.','安排'],['belong','v.','属于；有归属感'],['guidance','n.','指导'],['remain','v.','留下']], 'rather than merely accept her help：rather than 表示“而不是”；注意 choose 与 accept 的意思对比。','为什么玛丽拉的决定越来越难？用 because 解释两个原因。');
add('anne',3,'An Apology with Many Words','长长的道歉','B1',`
Anne cared deeply about how people saw her. She disliked her red hair and often imagined looking completely different. When Mrs Rachel Lynde visited Green Gables and spoke unkindly about her appearance, Anne could not hide her anger. She answered sharply and said things that shocked the adults. To Anne, the visitor had started the trouble. To Marilla, Anne's response had crossed a line.

Marilla told Anne that she must apologise. Anne refused at first. She could still hear the hurtful comments in her mind, and saying sorry seemed to mean agreeing that they were acceptable. She stayed angry and unhappy. The problem was not simply that she needed to learn a polite sentence. She needed to understand how to take responsibility for her own words without pretending that the other person's words had not hurt.

Matthew spoke to her more gently. He did not enjoy arguments and did not offer a long lesson about manners. His kindness made it easier for Anne to think beyond her first feelings. In time, she agreed to apologise. When the moment came, she did it in her own dramatic style, using far more words and feeling than Marilla had expected. The apology was almost a performance, but it was also an attempt to repair the situation.

Mrs Lynde was moved enough to become more friendly. Anne was relieved, although she had not suddenly stopped caring about her appearance. Marilla, meanwhile, had more to think about than a simple victory over bad behaviour. The girl living in her house felt everything strongly, and ordinary corrections could become great emotional events. Living together would require more than rules alone. It would require understanding what lay behind a reaction. Anne had learned that anger did not give her permission to say anything she wished. The adults also had a chance to notice how easily careless comments could wound a child who was already afraid of being judged. An apology ended the argument, but understanding would take longer.
`, '外貌评论激怒安妮，玛丽拉要求她道歉。改写区分了两件事：承认自己说话伤人，并不等于认同别人对自己的伤害。',[['appearance','n.','外貌'],['apologise','v.','道歉'],['responsibility','n.','责任'],['careless','adj.','不经意的；粗心的']], 'without pretending…：without 是介词，后接 doing。例：She apologised without pretending that she was not hurt.','安妮为什么不愿道歉？她最后学到了什么？');
add('anne',4,'A Dress for the Concert','音乐会的新裙子','A2',`
Anne wanted a dress with large, fashionable sleeves. She had seen other girls wearing them and thought they looked beautiful. Her own clothes were simple and useful. Marilla believed that this was enough. A dress did not need extra cloth just to make someone feel important. Anne tried to accept this, but the wish stayed in her mind whenever she watched her friends getting ready for special events.

Matthew noticed more than he said. He did not understand much about fashion, but he understood that Anne felt different from the other girls. He wanted to give her something that would make her happy. Buying such a dress was not an easy task for a shy man who disliked speaking in shops. Even asking the right question seemed difficult. Still, he decided to make the effort.

With help, Matthew arranged for a dress that had the sleeves Anne wanted. When she saw it, she was almost unable to believe that it belonged to her. The dress mattered partly because it was pretty. More importantly, someone had listened to a wish she thought was too small or foolish to be taken seriously. Matthew had not given her a speech about affection. He had shown it through a choice.

When Anne prepared for the concert, the new dress helped her feel that she could stand among the other girls without hiding. She still had red hair, and she was still the same Anne who made mistakes and talked too much. Cloth could not change those things, nor did it need to. The gift did not solve every worry she had about herself. It simply made one evening brighter and gave her another reason to feel loved at Green Gables. For Matthew, the important part was not the style of the sleeves. It was the look on Anne's face when she discovered that her happiness had been worth his trouble. Quiet people could give very clear answers without many words.
`, '马修注意到安妮想要一条时髦裙子。他克服不擅长购物交流的困难，为她准备礼物。真正重要的是她的愿望被看见。',[['sleeve','n.','袖子'],['fashionable','adj.','时髦的'],['effort','n.','努力'],['affection','n.','喜爱；关爱']], 'someone had listened to a wish…：过去完成时强调她发现裙子前，已经有人留意她的愿望。','这件礼物除了漂亮，还为什么让安妮感动？');
add('women',1,'Breakfast on Christmas Morning','圣诞节的早餐','A2',`
The four March sisters woke up on Christmas morning with different wishes. Meg liked beautiful things. Jo wanted books and adventures. Beth was happiest near music and home. Amy hoped to become an artist and often thought about what looked proper. Their family did not have much money, and their father was away. The girls loved one another, but that did not stop them from feeling disappointed about the things they could not have.

They had been looking forward to breakfast when their mother returned with news. A poor family nearby had almost nothing to eat. The children were cold, and their mother needed help. Mrs March asked her daughters whether they would share their breakfast. For a moment, the girls thought about the food in front of them. Being generous sounded easy until it involved giving up something they had been waiting for.

Then they began to prepare the food to take away. They went with their mother to the family's small home. Inside, the difference between the two households was clear. The March sisters had been thinking about what was missing from their own Christmas. Here, people needed the most ordinary things: warmth, food and someone willing to notice them. The girls helped where they could and watched the children begin to eat.

When they left, their own wishes had not disappeared. Jo still liked books, and Amy still cared about pretty things. Yet they now understood their situation differently. Their home contained safety, love and the possibility of helping someone else. Later celebrations would bring pleasure, but this part of the morning had already given them something worth remembering. They had acted together instead of only discussing what a good person ought to do. The breakfast was gone, but the day did not feel smaller because of it. On the way home, the sisters could talk about a Christmas gift they had given rather than only the gifts they hoped to receive. That changed the conversation around their own table.
`, '四姐妹起初为缺少礼物而失落，随后把期待的早餐送给更困难的家庭。她们没有因此失去个人愿望，但对自己的生活有了不同理解。',[['generous','adj.','慷慨的'],['household','n.','家庭；一户人家'],['warmth','n.','温暖'],['give up','短语','放弃']], 'rather than only the gifts…：比较她们谈论的重点由“收到”转向“给予”。','如果是你，会不会舍不得早餐？用英语解释，然后总结姐妹们的选择。');
add('women',2,'A Window between Neighbours','邻居之间的一扇窗','B1',`
Jo March was curious about the large house next door. A boy named Laurie lived there with his grandfather. From outside, the house seemed to contain everything that money could buy. Yet Laurie often looked lonely. Jo's own home was much busier. Her sisters argued, worked, laughed and made noise. It was difficult for her to imagine living in beautiful rooms without that constant company.

When Laurie was unwell, Jo had an opportunity to visit him. She brought her energy into the quiet house and did not behave as if every object were too expensive to touch. She talked openly, asked questions and found things to laugh about. Laurie enjoyed her visit because she treated him as a possible friend rather than as a rich boy who needed careful, formal attention.

Jo also met his grandfather, Mr Laurence. She discovered that he was not simply the frightening old man she had imagined. He could be serious, but he cared about Laurie and was interested in the family next door. Jo's direct way of speaking sometimes led her into trouble, yet it could also make a formal room feel more human. By the end of the visit, the distance between the two houses seemed smaller.

Friendship did not remove the differences between them. Laurie still had comforts that the March family could not afford, and the sisters still had worries about money. But neither house contained everything its residents needed. One had wealth and space; the other offered a kind of lively belonging that Laurie missed. As visits became more natural, both families gained something. Jo found a companion who enjoyed stories and adventures. Laurie found people who expected him to join in rather than sit alone at a window. The connection began with curiosity, but it grew because someone crossed the small distance between looking at another person's life and actually entering it. A neighbour could become a friend only when one of them was willing to knock.
`, '乔探望生病的劳里，发现富裕生活并不自动等于快乐。两家差异仍在，但主动交流带来互相需要的陪伴。',[['formal','adj.','正式拘谨的'],['wealth','n.','财富'],['resident','n.','居住者'],['companion','n.','伙伴']], 'rather than sit alone：rather than 连接两个对照的动作；理解 join in 与 sit alone 的对比。','劳里和乔分别从这段友谊获得了什么？');
add('women',3,'Beth and the Piano','贝丝与钢琴','A2',`
Beth March loved music, but she did not like being the centre of attention. Her family's piano was old, and it could not always make the sounds she wanted. In the house next door, Mr Laurence had a much better instrument. The thought of playing it excited Beth. The thought of entering the house and meeting its serious owner made her afraid. Her wish and her shyness pulled her in opposite directions.

Mr Laurence learned about her love of music. Instead of demanding that she come and perform for him, he made it easier for her to visit quietly. Beth could play when she believed nobody would trouble her. Little by little, she began going next door. Once she was seated at the piano, she could forget some of her fear. Her hands found something to say that her voice often could not.

The music meant something to Mr Laurence as well. Beth reminded him of someone he had loved and lost. He did not need her to explain every feeling. Hearing her play was enough. Beth wanted to thank him, but a great speech would have been difficult for her. She made him a pair of slippers. It was a small, careful gift, made with time and affection rather than much money.

Later, a piano arrived for Beth. The surprise was so great that she found courage she had not expected. She went to thank Mr Laurence herself. Their friendship was unusual in age but clear in feeling. Neither needed the other to become a different kind of person. Beth could remain quiet, and Mr Laurence could remain serious. Music and thoughtful actions allowed them to meet between those differences. The new instrument was wonderful, but the deeper gift was the discovery that her quiet interests mattered to someone outside her family. She had not won attention by becoming the loudest person in the room. She had been heard because someone was willing to listen in another way.
`, '贝丝害羞却热爱音乐。劳伦斯先生让她自在地弹琴，她则用亲手做的拖鞋道谢。故事展现了无需大声表达的关爱。',[['instrument','n.','乐器'],['shyness','n.','害羞'],['slippers','n.','拖鞋'],['courage','n.','勇气']], 'Instead of demanding…：instead of 后接 doing。意为“他没有要求她当众表演，而是……”','为什么让贝丝安静地练琴，比要求她表演更体贴？');
add('women',4,'Words That Could Not Be Replaced','无法找回的文字','B1',`
Jo spent many hours writing stories. Her pages held not only words but also plans, effort and the excitement of making an imagined world feel real. Amy, her younger sister, wanted to be included in the older girls' activities. When she was left out of an outing, her disappointment turned into anger. She chose a punishment that would hurt Jo deeply: she burned the manuscript on which Jo had worked so hard.

When Jo discovered what had happened, she was furious. An apology could not bring the pages back. She felt that Amy had destroyed something that belonged to her inner life, not merely an object she could buy again. Even when their mother encouraged forgiveness, Jo could not simply decide to feel calm. The sisters remained close in the house but far apart in their feelings.

Later, Amy followed Jo and Laurie when they went skating. Jo was still angry and did not make sure that Amy heard the warning about dangerous ice. Then the ice broke beneath Amy. In that frightening moment, Jo's anger lost its importance. What mattered was getting her sister out of the water. Laurie helped rescue Amy, and the danger forced Jo to face what might have happened.

The story does not make the burned pages unimportant. Amy's action was cruel, and Jo had a reason to be hurt. But Jo also recognised how dangerous it could be to let anger decide every response. She talked with her mother about the struggle to control a strong temper. Forgiveness was not the same as saying that nothing had happened. It meant choosing what relationship she wanted after acknowledging the harm. The manuscript could not be restored, and trust would need care. Yet her sister was alive, and there was still a future in which both of them could behave differently. For Jo, the hardest work that day was not writing a new story. It was learning how to live with an injury without allowing it to guide every choice she made next.
`, '艾米烧毁乔的手稿，乔非常愤怒。冰上事故让她重新面对情绪与亲情。改写没有把原谅等同于否认伤害，而强调之后如何选择。',[['manuscript','n.','手稿'],['furious','adj.','愤怒的'],['rescue','v.','营救'],['forgiveness','n.','原谅']], 'on which Jo had worked：介词 + which 引导定语从句，相当于 the manuscript which Jo had worked on。','原谅与“事情不重要”有什么区别？先复述事件，再表达观点。');
add('oz',1,'The House That Flew','飞起来的房子','A2',`
Dorothy lived with Aunt Em and Uncle Henry in Kansas. Their home was small, and the land around it often looked grey and dry. Dorothy's dog Toto brought movement and fun into this quiet life. One day, the sky began to change. Uncle Henry watched it carefully and knew that a dangerous storm was coming. Aunt Em called Dorothy to hurry into the shelter beneath the house.

Toto hid, and Dorothy tried to find him before following her aunt. While she was still inside, the wind became stronger. Suddenly the house shook and rose into the air. Dorothy felt the floor move beneath her feet. She could not go outside or stop what was happening. She held Toto and waited while the house travelled through the storm. At last, tired by fear and movement, she fell asleep.

When she woke, the house was still. Dorothy opened the door and saw a place unlike the Kansas fields. There were bright colours, green plants and people looking at her with surprise. She learned that the falling house had killed a cruel witch and freed the people who had lived under her rule. They were grateful, but Dorothy had not planned any of it. She was a child who wanted to go home.

A kind witch explained that a powerful person in the Emerald City might be able to help. Dorothy was given silver shoes that had belonged to the dead witch, and she was told to follow a road made of yellow bricks. The new land was beautiful, but beauty did not remove her worry about Aunt Em. Dorothy gathered what she needed and began walking with Toto. She did not know how long the journey would take or whom she would meet. She knew only the direction of the road and the reason for following it. Behind every bright, unfamiliar thing was the same simple wish: to reach the people who were wondering where she had gone.
`, '龙卷风把多萝西与托托带到陌生国度。她得到银鞋，沿黄砖路去寻找回家的帮助。此处依据小说的银鞋设定，不采用电影中的红鞋。',[['shelter','n.','避难处'],['storm','n.','暴风雨'],['brick','n.','砖'],['grateful','adj.','感激的']], 'had belonged to：表示鞋子在当时之前属于谁。注意小说场景中 fell、woke、opened 等过去式。','多萝西面对美丽的新地方，为什么仍然想回家？');
add('oz',2,'The Scarecrow on the Pole','木杆上的稻草人','A2',`
As Dorothy followed the yellow road, she came to a field. A scarecrow stood on a pole among the plants. His clothes were filled with straw, and his face was painted on a sack. Dorothy would have walked past if he had not moved and spoken to her. He wanted to come down, but he could not leave the pole without help. Dorothy lifted him free and placed him on the ground.

The Scarecrow thanked her and asked where she was going. When she mentioned the Wizard of Oz, he wondered whether the Wizard could give him a brain. He believed that a head full of straw could not be useful. Dorothy did not know whether brains could be handed out as gifts, but she saw no reason why he could not come and ask. Soon they were walking along the road together.

Travelling with him was different from travelling alone. He did not need food or sleep, although he was afraid of fire. He asked questions about Dorothy's home and listened when she explained why she wanted to return. Some things that seemed ordinary to her were completely new to him. By trying to explain them, she noticed how much she cared about a place that other people might find dull.

The Scarecrow spoke as if he had no sense at all. Yet he could listen, compare ideas and think about possible problems. Dorothy did not stop the journey to give him a lesson about this difference. They simply kept moving, and his actions would have more chances to show what he could do. The road now had two travellers with two wishes: one wanted a home, and the other wanted proof that he could think. Neither had received what they were seeking. Even so, helping him down from the pole had already changed the journey. Dorothy had a companion, and the Scarecrow was no longer standing still while life passed around him. He could begin discovering the world he had only watched from one small field.
`, '多萝西帮助稻草人离开木杆。他希望得到大脑，却已经表现出提问与思考的能力。两人从此同行。',[['scarecrow','n.','稻草人'],['pole','n.','杆子'],['straw','n.','稻草'],['proof','n.','证明']], 'whether the Wizard could…：whether 引导宾语从句，表示“是否”。从句保持陈述语序。','稻草人认为自己缺少什么？他的哪些行为让你产生不同判断？');
add('oz',3,'Oil for a Still Traveller','给停住的旅人加油','A2',`
Dorothy and the Scarecrow reached a place with many trees. There they heard a weak sound that seemed to be asking for help. A man made of tin stood completely still, holding an axe. Rain had fallen on him, and his joints had become rusty. He could see and hear the world around him, but he could not move through it. An oil can nearby offered the answer if someone would use it.

Dorothy put oil on his joints while the Scarecrow helped. Slowly, the Tin Woodman began to move. First he could speak more clearly; then he could lower his arms and take a step. He thanked his rescuers and explained how long he had been waiting. His body was strong in some ways, but a small problem in the places where its parts met had stopped everything.

When he learned about their journey, he asked to join them. He wanted the Wizard to give him a heart. Without one, he believed, he could not truly feel love. The Scarecrow thought a brain was more useful. The Tin Woodman thought a heart was more important. Dorothy listened to their different hopes. She did not know which gift mattered more, and she did not think she needed either gift to know that she missed home.

As they continued, the Tin Woodman was careful about the small creatures on the path. He did not want to harm something that could not protect itself. His kindness was visible even while he insisted that he had no heart. The group now contained friends who believed that the most important part of themselves was missing. Yet each had already done something valuable for another traveller. They still planned to ask the Wizard for help, but the journey was quietly collecting evidence they had not learned to recognise. Thinking did not always require confidence in one's brain, and kindness did not always wait for permission from a heart. For the moment, they walked together and carried the oil can in case it was needed again.
`, '铁皮人因为生锈无法活动，朋友们用油帮助他。他希望得到一颗心，但已经会体贴小生命。',[['tin','n.','锡；镀锡金属'],['joint','n.','关节'],['rusty','adj.','生锈的'],['harm','v.','伤害']], 'while he insisted…：while 在这里表示同时发生；观察人物“说的话”和“做的事”的对照。','稻草人和铁皮人想要的东西有什么不同？各用一句说明理由。');
add('oz',4,'A Lion Who Felt Afraid','会害怕的狮子','B1',`
A loud roar stopped the travellers as they passed through the forest. A lion appeared and frightened the Scarecrow and the Tin Woodman. When he turned towards Toto, Dorothy became angry. Her little dog was much smaller than the Lion and could not defend himself. She stood up to the great animal instead of running away. The Lion's behaviour changed, and he admitted that he had acted badly.

Behind his frightening appearance, the Lion carried a secret shame. He was often afraid. Other animals expected him to be brave because he was large and powerful. Their expectations did not remove his fear; they made it harder to confess. He imagined that somewhere there might be a supply of courage which would stop him from ever feeling nervous again. When he heard about the Wizard, he wanted to ask for some.

Dorothy allowed him to join the group. Now the road carried a girl seeking home and three companions seeking qualities they believed they lacked. Their wishes were different, but obstacles on the journey affected all of them. A dangerous place could not be crossed merely by talking about what each person hoped to receive. They had to use the abilities they already possessed and help one another move forward.

The Lion would have opportunities to act while still feeling afraid. This was different from his original idea of courage. He had hoped that bravery meant the complete absence of fear. In practice, it could mean noticing a danger, wanting to escape and nevertheless choosing to help. His companions did not need him to become fearless before accepting him. They needed him to keep trying when a situation called for his strength. Dorothy, too, had shown courage without stopping to name it. She had defended a small friend against a much larger animal. The journey towards the Wizard remained unfinished, but the meaning of the travellers' wishes was already beginning to change. What they wanted to be given might also be something they could learn to recognise in their own actions.
`, '狮子承认自己害怕。他起初以为勇气就是彻底不恐惧，旅程却让他有机会在害怕时仍选择帮助同伴。',[['roar','n.','吼声'],['defend','v.','保护；防卫'],['confess','v.','承认'],['nevertheless','adv.','然而；仍然']], 'qualities they believed they lacked：qualities 后是省略关系词的定语从句；they believed 插在其中，先抓住“他们缺少的品质”。','勇敢是不是等于不害怕？结合文中的行为回答。');
add('alice',1,'A Rabbit with a Watch','带表的兔子','A2',`
Alice was sitting beside her sister on a warm day. Her sister was reading, but the book did not interest Alice. There were no pictures to catch her attention, and she was beginning to feel sleepy. She thought about making something with flowers, but getting up seemed like too much work. Then a white rabbit ran past her. At first, this did not seem especially surprising.

What changed everything was the watch. The Rabbit took it out, looked at the time and hurried on as if he were late for an important meeting. Alice had never seen a rabbit with a watch before. Suddenly she was no longer sleepy. She followed him across the field and watched him disappear into a hole. Without thinking carefully about how she would return, she went after him.

The passage turned downwards, and Alice found herself falling. It was a very long fall, or at least it seemed long enough for many thoughts. She looked at the things around her and wondered where she was going. She also thought about her cat and about what people would say when she returned. Ordinary questions continued to enter her mind even while something completely extraordinary was happening to her.

At last, she landed without being badly hurt. The Rabbit was still ahead, so she followed again. Soon she found herself in a hall with several locked doors. The place was quiet and strange, and the Rabbit had disappeared. Her curiosity had carried her away from the familiar riverbank into a situation she did not understand. This was exciting, but it also meant that she could not simply ask her sister what to do. Alice began looking around for clues. A small table and a key caught her attention. The adventure had started with a question about a rabbit's watch. Now she had a more practical question to answer: which door, if any, would let her continue? She picked up the key and began to try the locks.
`, '爱丽丝被带怀表的白兔吸引，追进兔子洞，落入有许多锁门的大厅。好奇心推动她出发，接下来她必须自己解决问题。',[['rabbit','n.','兔子'],['curiosity','n.','好奇心'],['extraordinary','adj.','不同寻常的'],['clue','n.','线索']], 'found herself falling：find + 宾语 + doing，表示发现自己处于某种正在发生的状态。','什么让爱丽丝由无聊变得好奇？你觉得她追进去前应该考虑什么？');
add('alice',2,'Too Small for the Key','小得够不到钥匙','A2',`
In the hall, Alice discovered a tiny door behind a curtain. The little key fitted its lock, and she could see a beautiful garden beyond it. There were flowers and paths that looked much more inviting than the hall. Unfortunately, the opening was far too small for her. She could put her head near it, but the rest of her body could not follow. Seeing a way forward was not the same as being able to use it.

On the table, she found a bottle with a label inviting her to drink. Alice examined it before taking any. Then she drank and began to become smaller. The change was astonishing. Furniture that had seemed ordinary now rose above her. At last, she was small enough to go through the little door. She felt pleased until she remembered that the key was still on the table.

From her new height, reaching the key was impossible. Alice tried to climb, but the table was too smooth. The solution to one problem had created another. Nearby, she found a small cake with a message telling her to eat it. She hoped that another change in size might help. Yet she could not control exactly what would happen, and growing larger brought a different set of difficulties.

Alice became upset. She wanted one clear instruction that would put everything right, but the hall offered objects whose results were uncertain. Each time she changed, she had to understand the same room again from a different position. The garden remained attractive, although getting there was no longer a simple matter of finding the correct door. She needed to think about the order of her actions as well as the actions themselves. A key was useful only if she could reach it; being small was useful only if the door was open. Her strange problem had an ordinary shape beneath it: before changing a situation, it helped to consider what she would need afterwards. For now, however, Alice was still learning by making mistakes.
`, '爱丽丝变小后虽然能过小门，却够不到留在桌上的钥匙。变大变小反复带来新问题，可观察“行动顺序”的重要性。',[['tiny','adj.','极小的'],['label','n.','标签'],['smooth','adj.','光滑的'],['afterwards','adv.','之后']], 'small enough to go：形容词 + enough + to do；too small for her 则表示小得不适合她通过。','如果你在场，会怎样安排拿钥匙、开门和变小的顺序？');
add('alice',3,'A Question from the Caterpillar','毛毛虫的问题','B1',`
Alice met a Caterpillar sitting on a mushroom. He did not greet her with the friendly help she had hoped for. Instead, he asked who she was. This sounded like an easy question, but Alice had already changed size several times. She remembered being herself that morning, yet the events since then had made even that answer feel uncertain. She tried to explain, and the Caterpillar did not make the conversation easier.

He spoke briefly and expected Alice to understand him. When she became frustrated, he offered little comfort. Alice wanted useful information, not another argument about whether her words made sense. Nevertheless, she stayed. In this strange place, even an unpleasant conversation might contain something she needed to learn. Leaving immediately would protect her pride but would not necessarily solve her problem.

Before he left, the Caterpillar told her that different sides of the mushroom could change her height in opposite ways. Alice took pieces and experimented carefully. At first, she did not get the balance right. One change made her neck so long that another creature misunderstood what she was. She had to respond to a new accusation while also trying to put her body into a more useful shape.

Eventually, practice gave her more control. She could carry the mushroom pieces and use them when she needed a different size. This did not explain everything about Wonderland, but it gave her a tool. The Caterpillar's first question still mattered in another way. Alice had discovered that her appearance and circumstances could change quickly, while her efforts to understand, remember and choose continued. She did not need a perfect answer about herself before taking the next useful step. Nor did she have to accept every judgement made by a creature who saw only one strange moment of her life. With the pieces in her hands, she could begin moving more deliberately. She was still in an uncertain world, but she was no longer entirely without a way to respond to it.
`, '毛毛虫问“你是谁”，使不断变大变小的爱丽丝难以回答。蘑菇让她逐渐掌握调整身高的方法，也引出身份与他人判断的问题。',[['caterpillar','n.','毛毛虫'],['mushroom','n.','蘑菇'],['accusation','n.','指责'],['deliberately','adv.','有意识地']], 'Leaving immediately would…：动名词短语作主语；注意 leaving 不是这个句子的谓语。','爱丽丝如何由失控变得更能应对环境？用 at first / eventually 描述。');
add('alice',4,'Tea without an Answer','没有答案的茶会','B1',`
Alice came upon a tea table with the Hatter, the March Hare and a sleepy Dormouse. There appeared to be plenty of room, but the hosts told her there was none. Alice sat down anyway. She expected the ordinary rules of a tea visit: people might offer a drink, introduce themselves and make conversation. Instead, she entered a discussion in which the words were familiar but the logic seemed to move away whenever she approached it.

The Hatter asked a riddle. Alice was pleased because a question suggested the possibility of an answer. She thought carefully and tried to work it out. Then she discovered that the person who had asked it did not know the answer himself. Her effort had not brought her closer to a solution because there was no agreed solution waiting for her. She felt that the conversation had wasted her time.

Time, however, became another strange subject. The Hatter spoke about it as if it were a person with whom he had quarrelled. The party seemed trapped in tea time. When places became untidy, the guests moved around the table instead of finishing the meal in the usual way. Alice tried to question the arrangement, but each explanation produced more confusion. The Dormouse's story was interrupted, and nobody seemed interested in making things clear for her.

At last, Alice decided to leave. She did not solve the riddle or persuade the others to behave according to her idea of good manners. Sometimes an unsuccessful conversation ended not with agreement but with recognising that it was going nowhere. Yet the scene also challenged her confidence that familiar language always carried a familiar meaning. A question might be asked without knowledge behind it; a polite-looking gathering might not make a guest feel welcome. Alice walked away with more irritation than understanding. Even so, choosing to leave was an action she could take for herself. Wonderland could continue arguing around its endless table. She still had a journey to make, and she did not have to spend all of it waiting for an answer that nobody intended to give.
`, '茶会上的熟悉词语不遵守正常逻辑，谜语甚至没有公认答案。爱丽丝最终选择离开，故事也让读者留意提问、礼貌与交流的实际意义。',[['riddle','n.','谜语'],['logic','n.','逻辑'],['quarrel','v.','争吵'],['endless','adj.','无尽的']], 'with recognising…：with 是介词，后面用 recognising。not with A but with B 表示“不是以A，而是以B”。','爱丽丝为什么觉得茶会令人沮丧？离开是否是合理选择？');
})();
